---
title: "Gotcha: golang's keyward defer behavior"
date: 2022-11-20
---

## Example 1 - what will be the output of this snippet?

```go

package main

import "fmt"

type T int

func (t T) A() T {
 fmt.Print(" A ")
 return t
}

func (t T) B() T {
 fmt.Print(" B ")
 return t
}

func main() {
 var v T
 defer v.A().B()
 v.B().A()

}

 

```

<details>
  <summary>Answer</summary>
  A  B  A  B
</details>

## Example 2 - what will be the output of this snippet?
```go
func TestDeferGotcha(t *testing.T) {

	fmt.Println(foo(0))
}

func foo(x int) int {
	defer func() {
		x++
		fmt.Printf("x = %d\n", x)
	}()
	return x
}

```
<details>
  <summary>Answer </summary>
x = 1
0
</details>

## Example 3 - what will be the output of this snippet?
```go
for i := 0; i <= 3; i++ {
	defer fmt.Print(i)
}
```
<details>
  <summary>Answer </summary>
3
2
1
0
</details>

## Breakdown

[Reference to the spec](https://go.dev/ref/spec#Defer_statements)


> 
Each time a "defer" statement executes, the function value and parameters to the call are evaluated as usual and saved anew but the actual function is not invoked. Instead, deferred functions are invoked immediately before the surrounding function returns, in the reverse order they were deferred. That is, if the surrounding function returns through an explicit return statement, deferred functions are executed after any result parameters are set by that return statement but before the function returns to its caller. If a deferred function value evaluates to nil, execution panics when the function is invoked, not when the "defer" statement is executed. 

